G14 - Refactored scripts

diff --git a/scripts/02-build-and-upload-lambda b/scripts/02-build-and-upload-lambda
--- a/scripts/02-build-and-upload-lambda
+++ b/scripts/02-build-and-upload-lambda
@@ -1,13 +1,37 @@
 #!/usr/bin/env bash
+set -e
 source ../config/settings
 
 # validate user input
-if [[ $# -ne 1 ]]; then
+if [[ $# -ne 2 ]]; then
   echo
-  echo "Wrong number of parameters. Usage: ./02-build-and-upload-lambda [test|prod]"
+  echo "Wrong number of parameters. Usage: ./02-build-and-upload-lambda [test|prod] [CreateMessage|RegisterUser]"
   echo
   exit 1
 fi
 
-(cd ../functions/messages/create/ && ./build_and_deploy $1)
-(cd ../functions/users/register/ && ./build_and_deploy $1)
+# change directory according to the function
+if [[ $2 == $FUNCTION_CREATE_MESSAGE_NAME ]]; then
+  DIR="../functions/messages/create/"
+elif [[ $2 == $FUNCTION_REGISTER_USER_NAME ]]; then
+  DIR="../functions/users/register/"
+fi
+cd $DIR
+
+# install dependencies
+go get -d ./...
+
+# compile Go
+GOARCH=amd64 GOOS=linux go build -o $2
+
+# change permissions
+chmod u+x $2
+
+# zip executable
+zip $2.zip $2
+
+# upload zip to S3
+aws --profile $AWS_PROFILE s3 cp $2.zip s3://$BUCKET_NAME_PREFIX-$1/
+
+# cleanup
+rm $2.zip $2
